name: Build + test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build_and_test:
    name: ${{ matrix.os }} - ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        build_type: [ Release ]
        include:
          - os: ubuntu-latest
            build_type: Coverage

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: '0'

      - name: Install deps
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update
          sudo apt install libudev-dev

      - name: Configure and build
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -G Ninja -S . -B build
          cmake --build build -j

      - name: Test
        run: ctest --test-dir build -j --output-on-failure

      - name: Check test coverage and generate report
        if: ${{ matrix.build_type == 'Coverage' }}
        uses: threeal/gcovr-action@v1.2.0
        with:
          decisions: true
          fail-under-decision: 70
          fail-under-function: 70
          fail-under-line: 70
          filter: |
            include/.*
            src/.*
          print-summary: true
          xml-out: cov.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          disable_search: true
          files: ./cov.xml
          flags: unittests
          plugins: noop
          token: ${{ secrets.CODECOV_TOKEN }}
